### ISSUE TITLE
APR - CMake build fails on 1.8.x

### ISSUE THREAD

**Issue by nono303** [nono303/win-build-scripts#1]
Hi @ylavic
I've opened a bug concerning APR - CMake build fails on 1.8.x see https://bz.apache.org/bugzilla/show_bug.cgi?id=66121
Also posted on https://www.apachelounge.com/viewtopic.php?p=41309#41309
on https://github.com/apache/apr/commit/55f413526c6864b666f241c079c6a4f2d836cf7d you mentionned 

> only tested that it didn't break unixes..

Any ideas of what can imply this issue?
Thx!

----

> Hi,
> on [Revision 1901932](https://svn.apache.org/viewvc?view=rev&rev=1901932) for /apr/apr/branches/1.8.x
> - Merge [r1897895](https://svn.apache.org/viewvc?view=rev&rev=1897895) from trunk
> CMake MSVC build fails with error:
>  ``` Creating library .\x64\Release\libapr-1.lib and object .\x64\Release\libapr-1.exp
>     wakeup.obj : error LNK2001: unresolved external symbol apr_socket_pipe_close
>     wakeup.obj : error LNK2001: unresolved external symbol apr_socket_pipe_create
>     .\x64\Release\libapr-1.dll : fatal error LNK1120: 2 unresolved externals
> ```  
> Here are my check & to qualify it:
>  - network_io/win32/socket_pipe.c & poll/unix/wakeup.c are present in CMakeLists.txt and compiled without errors before linking
>  - include/arch/win32/apr_arch_networkio.h define as extern apr_socket_pipe_create & apr_socket_pipe_close
>  - poll/unix/wakeup.c include apr_arch_networkio.h
>  - include/apr_networkio.h does NOT mention apr_socket_pipe_create & apr_socket_pipe_close
> 
> Any idea to fix this linking issue? (APR_DECLARE or public header export missing...)
> Thx!

**Comment by ylavic** [comment]
> Any ideas of what can imply this issue?

Sorry no, I barely know how cmake/windows builds work..
You probably should ask on the dev@apr.a.o mailing list though, for bigger audience.

**Comment by nono303** [comment]
Thx @ylavic for your reactivity!
I'll ask on the [dev@apr.a.o](mailto:dev@apr.a.o) mailing list

**Comment by nono303** [comment]
Hi @ylavic 
Found the issue & had a patch proposal (see https://bz.apache.org/bugzilla/show_bug.cgi?id=66121)
I'll inform [dev@apr.a.o](mailto:dev@apr.a.o)

**Comment by nono303** [comment]
Hi @ylavic
I maybe miss something but... How to contact [dev@apr.a.o](mailto:dev@apr.a.o) ??

```
could not be delivered to the following recipient(s):

     dev@apr.a.o (unrecoverable error)
could not be delivered to the following recipient(s):

     dev@apr.ao (unrecoverable error)
```
